targets:
  $default:
    builders:
      artemis:
        options:
          schema_mapping:
            - output: lib/graphql/graphql_schema.dart
              schema: lib/graphql/schema.graphql
              queries_glob: lib/graphql/query.graphql