name: yx_statistics_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3  
  # https://github.com/google/json_serializable.dart/tree/master/example
  json_annotation: ^3.0.0  
  # https://pub.dev/packages/graphql
  graphql: ^3.0.0
  # https://pub.dev/packages/graphql_flutter
  graphql_flutter: ^3.0.0  
  # https://pub.dev/packages/artemis
  # flutter pub run build_runner build --delete-conflicting-outputs
  artemis: '^6.12.2-beta.1'
  # Because fl_chart 0.11.1 depends on equatable ^1.1.1 and no versions of fl_chart match >0.11.1 <0.12.0, fl_chart ^0.11.1 requires equatable ^1.1.1.
  # equatable: ^0.6.1
  meta: '>=1.0.0 <2.0.0'
  gql: '>=0.7.3 <1.0.0'
  # https://github.com/imaNNeoFighT/fl_chart
  fl_chart: ^0.11.1
  # https://mobx.netlify.app/getting-started
  mobx: ^1.0.0
  flutter_mobx: ^1.0.0
  # https://pub.dev/packages/yaml_config
  yaml_config: ^0.1.2
  # https://pub.dev/packages/url_launcher
  url_launcher: ^5.5.0
  # https://pub.dev/packages/font_awesome_flutter
  font_awesome_flutter: ^8.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
  json_serializable: ^3.0.0
  gql_code_gen: ^0.1.0
  mobx_codegen: ^1.0.0
  # https://pub.dev/packages/flutter_launcher_icons
  flutter_launcher_icons: ^0.7.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon.png'

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # https://flutter.dev/docs/development/ui/assets-and-images#specifying-assets
  assets:
    - assets/
    - assets/fonts/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: FZLanTingYuan
      fonts:
        - asset: assets/fonts/FZLanTYJW_Xian.ttf
    - family: romantic_garden
      fonts:
        - asset: assets/fonts/romantic_garden.ttf
