# production environment configurations
production:
  endpoint: http://statistics.ynu.edu.cn/graphql
  enableDetailPage: false
# debug environment configurations
debug:
  endpoint: http://localhost:3000/graphql
  enableDetailPage: true